Repository zekehuntergreen/comsem, pull requests merged in 2023-02, with the labels that each got.

#170 143 setup mic start and stop function 1
  ComSemApp/templates/ComSemApp/student/assessment.html
  ComSemApp/templates/ComSemApp/student/assessment_audio_recording.html
Labels: javascript

#177 176 background audio recording
  ComSemApp/static/ComSemApp/js/ComSemRecording-opus-background.js
  ComSemApp/templates/ComSemApp/audio_recording_background.html
  ComSemApp/templates/ComSemApp/student/assessment.html
Labels: javascript

#175 174 add server side processing for practice problem post request data
  ComSemApp/student/views.py
  ComSemApp/utils.py
Labels: python

#189 187 add transcription field to speakingpracticeattempt model
  ComSemApp/migrations/0025_auto_20230214_0013.py
  ComSemApp/migrations/0026_transcribe_all.py
  ComSemApp/models.py
Labels: python, django

#192 191 no transcription error needs a fixin
  ComSemApp/student/views.py
Labels: bug, python, django

#193 182 write speakingpracticeresultsview get context data
  ComSemApp/student/views.py
Labels: python, django
